# Generated by Django 5.0.2 on 2024-03-11 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birth_date', models.DateField()),
                ('image', models.ImageField(default='profile_pics.jpg', upload_to='profile_pics')),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
